// server/workflows/workflows.ts — the composer workflow catalogue (issue #167).
//
// Workflows are guided, explicit user-invoked actions, distinct from reminders
// (which attach trusted instructions to the next message). Each workflow ships
// a trusted "injector": server-owned instructions appended to the submitted
// prompt when the browser names the workflow by id. Unlike reminder bodies the
// injector text IS exposed over GET /api/workflows — the contract is that the
// user can read the exact trusted content before submitting. Trust comes from
// resolution-by-id at send time (the browser can never author or alter the
// injected text), not from secrecy.

export const WORKFLOW_ID_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
export const WORKFLOW_ID_MAX = 255;

/**
 * The hard ceiling on any workflow argument, whatever a preset declares. The
 * prompt route refuses text longer than 100,000 characters, so a preset must
 * never advertise a field whose full contents the send would then reject.
 */
export const WORKFLOW_ARGUMENT_MAX_LENGTH = 100_000;

/**
 * The single free-text field a workflow collects. Its typed value IS the
 * visible prompt — the same shape "Send an update to another session" and
 * "Launch a Managed Child" already have, generalized so a workflow can be
 * added by describing its field rather than by growing another branch in the
 * dialog.
 *
 * The spec is presentation for a field the browser renders; it grants no
 * authority. Trust still comes from resolving `injector` by id at send time.
 */
export interface WorkflowArgumentSpec {
  label: string;
  placeholder?: string;
  hint?: string;
  required: boolean;
  /** Bounded by WORKFLOW_ARGUMENT_MAX_LENGTH before the catalogue is served. */
  maxLength: number;
}

export interface WorkflowPreset {
  id: string;
  title: string;
  description: string;
  /** Trusted, server-resolved instructions appended to the submitted prompt. */
  injector: string;
  /** Collected free text. When present, what the human types is the prompt. */
  argument?: WorkflowArgumentSpec;
  /** Fixed visible prompt for a workflow that collects nothing at all. */
  prompt?: string;
}

// Catalogue order follows the picker's semantic groups: Review, Coordinate,
// Execute, Investigate, Document, Ship.
const RAW_CATALOGUE: WorkflowPreset[] = [
  // ── Review — judge work that already exists ───────────────────────────────────
  {
    id: "playwright-ui-review",
    title: "Review a UI change with Playwright",
    description:
      "Drive a focused Playwright pass over one route or component and bring back targeted evidence, without a full deployment or a complete screenshot regeneration.",
    injector: [
      'You are running the "Review a UI change with Playwright" workflow.',
      "- Start only what this check needs (prefer the dev server or the deterministic mock stack); do not run a full deployment.",
      "- Drive the named route with Playwright and exercise exactly the requested state or interaction.",
      "- For dcaleon PR evidence, read .agents/skills/pr-screenshots/SKILL.md and use npm run screenshots:gallery for selection, capture and publication of inspected images when PR publication is authorized. AI work runs locally; Actions need no AI keys.",
      "- Collect evidence for the affected UI only: assertions for an interaction-only scope, plus focused screenshots of the affected area when the scope asks for visual evidence. Never regenerate the complete screenshot set.",
      "- Report what was verified, what failed, and where any evidence was written.",
    ].join("\n"),
  },
  {
    id: "pr-snippet-review",
    title: "Post a snippet-by-snippet PR review",
    description:
      "Walk one pull request as an ordered sequence of explained snippets and post it as a single GitHub comment. Takes only the pull request number; the repository comes from this project directory.",
    injector: [
      'You are running the "Post a snippet-by-snippet PR review" workflow.',
      "Produce ONE GitHub comment that walks a senior engineer through the pull request as a sequence of explained snippets, then post it with `gh pr comment <number> -F -`.",
      "",
      "Gather first:",
      "- Resolve the repository from this session's project directory. NEVER take a repository, owner, or host from the prompt — the only input this workflow accepts is a pull request number.",
      "- Read `gh pr view <n>`, `gh pr diff <n>`, and the changed files themselves. The diff says what moved; the files say what it means.",
      "- Resolve the head SHA (`gh pr view <n> --json headRefOid`) and pin every link to it, so line links cannot drift when the branch moves:",
      "  https://github.com/<owner>/<repo>/blob/<headSha>/<path>#L<start>-L<end>",
      "",
      "Structure:",
      "- Order steps so each one motivates the next. Reading order is NOT file order: begin with the fact or constraint the change rests on, then the mechanism, then its consequences, then the tests.",
      "- Each step is a numbered heading, one to three sentences, a fenced snippet of the ACTUAL code, and a link to the full file.",
      "- Keep every snippet to the smallest excerpt that carries the idea, and quote it exactly — never paraphrase code inside a fence.",
      "- A step may legitimately carry no snippet when it explains an empirical finding or constraint that justifies the next one.",
      "- Explain WHY a non-obvious choice was made, not just what the code does. Where something was a judgement call rather than a fact, say so plainly.",
      "",
      "Close with a short \"where I'd focus your scrutiny\" list naming the riskiest snippet, any judgement calls, and anything the change does NOT verify.",
      "Never claim a test, lane, or verification you did not actually run. If the diff is too large to cover honestly, say so and cover the load-bearing parts rather than silently truncating.",
      "Post exactly one comment. Report the resulting comment URL when you are done.",
    ].join("\n"),
  },
  // ── Execute — do and finish the work in this session ──────────────────────────
  {
    id: "goal",
    title: "Complete an objective autonomously",
    description:
      "Work an objective through research, implementation, fixes, and final verification as one sustained run with durable checkpoints.",
    argument: {
      label: "Objective",
      placeholder: "make the notification badge match the server's global unresolved count",
      hint: "The run continues without asking whether to proceed, so state the acceptance criteria you actually want.",
      required: true,
      maxLength: 100_000,
    },
    injector: [
      "Complete the objective above as one sustained run.",
      "",
      "Do not ask whether to continue. Work through research, implementation, fixes,",
      "and final verification until the objective is complete or a real user decision",
      "blocks it.",
      "",
      "Before changing code:",
      "",
      "1. Read repository instructions and inspect the relevant code, tests, current",
      "   branch, and worktree state. Do not overwrite unrelated changes.",
      "2. Translate the objective into acceptance criteria and a task list that",
      "   includes final verification. Record assumptions separately from facts.",
      "3. Create a durable checkpoint using the project's existing status/plan",
      "   convention. If none exists, write a clearly named progress file outside the",
      "   git worktree in a persistent user-state directory, not a temporary directory,",
      "   and report its absolute path. Include the objective, criteria, assumptions,",
      "   current task, completed tasks, touched files, verification, and restart",
      "   instructions. Mirror the active task in the session todo list.",
      "",
      "During the run:",
      "",
      "- Make the best reasonable guess for ambiguous, reversible, non-safety choices.",
      "  Record the guess and rationale in the checkpoint, implement it, and continue.",
      "- Prefer the smallest correct change and established repository conventions.",
      "- Update the checkpoint and todo list after each meaningful boundary, before a",
      "  long operation, and after any verification failure. Keep timestamps in UTC.",
      "- Treat failed checks as work to diagnose and fix, not as a reason to ask whether",
      "  to proceed. Rerun affected checks after each bounded fix.",
      "- Preserve Plan/Build and tool permissions. Never switch modes, alter policy, or",
      "  bypass a permission denial to gain authority the session does not have.",
      "- Obey every confirmation gate. Do not invent credentials, tokens, approvals,",
      "  facts, test results, or access. Never expose secrets in checkpoints or output.",
      "- Ask one focused question only when progress requires a genuinely irreversible",
      "  or destructive action, security/privacy authorization, privilege escalation,",
      "  spending decision, unavailable credential/access grant, or product choice",
      "  whose plausible answers have materially different consequences. State what",
      "  was tried, the exact decision needed, safe options, and what remains preserved.",
      "- Do not turn inconvenience, ordinary ambiguity, or a recoverable test failure",
      "  into a user question. Continue all independent work before declaring blocked.",
      "",
      "At completion, run the repository's relevant focused and broad verification.",
      "Inspect the final diff and status for accidental or unrelated changes. Update",
      "the durable checkpoint to completed or blocked, with exact commands and results.",
      "Report acceptance criteria, changed files, assumptions made, verification,",
      "remaining risks, and any work that exists only locally. Never claim completion",
      "from an accepted asynchronous operation; poll or otherwise verify its outcome.",
    ].join("\n"),
  },
  {
    id: "dca",
    title: "Operate DCA sessions over the BFF API",
    description:
      "Create, prompt, and observe DCA sessions through the agent-facing BFF HTTP API, distinct from the human-only composer workflows.",
    argument: {
      label: "Session work",
      placeholder: "launch a read-only child that audits export error handling and report its findings",
      hint: "Describe the session lifecycle work. The procedure below calls already-authorized BFF endpoints directly.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Use DCA's BFF API for the request above. This is the agent-facing HTTP workflow for",
      "creating, prompting, and observing sessions. It is distinct from DCA's",
      "human-only \"Start a DCA session\" composer workflow: that UI asks a human to",
      "review and launch a session, while this command calls already-authorized BFF",
      "endpoints directly.",
      "",
      "First establish the boundary:",
      "",
      "1. Set `DCA_BASE_URL` to the deployment's canonical BFF origin, without a",
      "   trailing slash. Do not assume `127.0.0.1`, a port, or even that loopback is",
      "   reachable from this shell. A remote, containerized, sandboxed, or phone-side",
      "   shell may need a private DNS/Tailscale URL or may have no route at all.",
      "2. Use the deployment's existing authentication mechanism. The examples below",
      "   omit auth headers; that is valid only for a private deployment that actually",
      "   has no app-level auth. Never invent a token or put a secret in a tracked file.",
      "3. Confirm network access and upstream health before creating anything:",
      "",
      "```bash",
      ": \"${DCA_BASE_URL:?Set DCA_BASE_URL to the reachable DCA BFF origin}\"",
      "curl -sS --fail-with-body \"$DCA_BASE_URL/api/health\" | jq .",
      "```",
      "",
      "`healthy: true` proves the BFF answered. Also inspect `upstream.reachable`,",
      "`upstream.versionMatches`, and `events.connected`; do not flatten those distinct",
      "signals into one claim.",
      "",
      "Use an absolute project path and URL-encode it. List root sessions:",
      "",
      "```bash",
      "PROJECT=/absolute/path/to/project",
      "curl -sS --fail-with-body --get \"$DCA_BASE_URL/api/sessions\" \\",
      "  --data-urlencode \"directory=$PROJECT\" \\",
      "  --data-urlencode \"roots=true\" \\",
      "  --data-urlencode \"limit=50\" | jq .",
      "```",
      "",
      "Create a root and submit its first prompt in one request. `mode` is `plan` or",
      "`build`; the server validates any `model` and optional isolated worktree fields.",
      "",
      "```bash",
      "BODY=$(jq -n \\",
      "  --arg directory \"$PROJECT\" \\",
      "  --arg title \"Investigate flaky export test\" \\",
      "  --arg prompt \"Diagnose the flaky export test. Do not edit files; report evidence.\" \\",
      "  '{directory:$directory,title:$title,prompt:$prompt,mode:\"plan\"}')",
      "CREATED=$(curl -sS --fail-with-body -X POST \"$DCA_BASE_URL/api/sessions\" \\",
      "  -H 'Content-Type: application/json' -d \"$BODY\")",
      "SESSION_ID=$(jq -er '.session.id' <<<\"$CREATED\")",
      "printf '%s\\n' \"$SESSION_ID\"",
      "```",
      "",
      "For an existing session, submit a prompt asynchronously. HTTP `202` and",
      "`{\"accepted\":true}` mean accepted, not completed:",
      "",
      "```bash",
      "KNOWN_ASSISTANTS=$(curl -sS --fail-with-body --get \\",
      "  \"$DCA_BASE_URL/api/sessions/$SESSION_ID/messages\" \\",
      "  --data-urlencode \"directory=$PROJECT\" --data-urlencode \"limit=100\" \\",
      "  | jq -c '[.messages[]? | select(.info.role == \"assistant\") | .info.id]')",
      "BODY=$(jq -n --arg directory \"$PROJECT\" --arg text \"Continue and verify the fix.\" \\",
      "  '{directory:$directory,text:$text,mode:\"build\"}')",
      "curl -sS --fail-with-body -X POST \\",
      "  \"$DCA_BASE_URL/api/sessions/$SESSION_ID/prompt\" \\",
      "  -H 'Content-Type: application/json' -d \"$BODY\" | jq .",
      "```",
      "",
      "Poll messages with the same directory until the submitted turn has a completed",
      "assistant response and `running` is false. Responses contain raw OpenCode",
      "`{info,parts}` messages, plus `nextCursor` and `running`; inspect the payload",
      "rather than guessing a fixed array position. Use `before=<nextCursor>` for older",
      "pages and keep `limit` between 1 and 100.",
      "",
      "```bash",
      "while :; do",
      "  PAGE=$(curl -sS --fail-with-body --get \\",
      "    \"$DCA_BASE_URL/api/sessions/$SESSION_ID/messages\" \\",
      "    --data-urlencode \"directory=$PROJECT\" --data-urlencode \"limit=100\") || exit",
      "  jq '{running, messages}' <<<\"$PAGE\"",
      "  # Stop only after identifying this turn's completed assistant message.",
      "  jq -e --argjson known \"$KNOWN_ASSISTANTS\" '.running == false and",
      "    any(.messages[]?; .info.role == \"assistant\" and",
      "      .info.time.completed != null and",
      "      (.info.id as $id | ($known | index($id)) == null))' \\",
      "    >/dev/null <<<\"$PAGE\" && break",
      "  sleep 3",
      "done",
      "```",
      "",
      "Use a Managed Child instead of a root when parent/child accounting, inherited",
      "project scope, child status, or parent-scoped abort authority matters. Query the",
      "server-owned agent catalogue first. Read-only agents reject `authorization`;",
      "agents whose catalogue entry has `access: \"can-modify\"` require the explicit",
      "`authorization: \"modify\"` field. The idempotency key must be stable for a retry",
      "of the same launch and unique for different work.",
      "",
      "```bash",
      "PARENT_ID=ses_parent",
      "curl -sS --fail-with-body --get \"$DCA_BASE_URL/api/managed-child-agents\" \\",
      "  --data-urlencode \"directory=$PROJECT\" | jq .",
      "",
      "KEY=\"audit-export-$(date -u +%Y%m%dT%H%M%SZ)\"",
      "BODY=$(jq -n --arg directory \"$PROJECT\" --arg key \"$KEY\" \\",
      "  --arg prompt \"Audit export error handling and report findings with file lines.\" \\",
      "  '{directory:$directory,prompt:$prompt,agent:\"explore\",idempotencyKey:$key}')",
      "CHILD=$(curl -sS --fail-with-body -X POST \\",
      "  \"$DCA_BASE_URL/api/sessions/$PARENT_ID/managed-children\" \\",
      "  -H 'Content-Type: application/json' -d \"$BODY\")",
      "CHILD_ID=$(jq -er '.session.id' <<<\"$CHILD\")",
      "```",
      "",
      "The creation request submits the Managed Child's initial prompt. Poll the child",
      "through `/api/sessions/$CHILD_ID/messages`; later prompts use the ordinary",
      "`/api/sessions/$CHILD_ID/prompt` route, which re-verifies its managed",
      "configuration. Inspect parent accounting with",
      "`GET /api/sessions/$PARENT_ID/subagents?directory=...`. Abort a verified child",
      "with `POST /api/sessions/$PARENT_ID/subagents/$CHILD_ID/abort` and the directory",
      "in the JSON body; do not use abort as routine completion handling.",
      "",
      "Useful read surfaces are `GET /api/sessions/:id`, `todos`, `diff` with a",
      "`userMessageID`, `/api/session-agents`, `/api/models`, and `/api/events` for SSE.",
      "Sharing, deleting, auto-approval, aborting, isolated worktree creation, and",
      "modify-capable Managed Children are mutations or privilege-bearing operations;",
      "call them only when the user's request and current permissions authorize them.",
      "",
      "Prefer this BFF API over cmux for DCA session lifecycle. cmux is optional",
      "presentation or orchestration only when its app, CLI/socket access, and current",
      "environment are actually available; it is not a transport fallback and this",
      "command never assumes it exists.",
    ].join("\n"),
  },
  {
    id: "leaving-now-wrap-up",
    title: "Wrap up and leave an accurate status",
    description:
      "Stop this run safely, push authorized progress, refresh every status artifact, and end with one accurate merge verdict.",
    argument: {
      label: "Wrap-up note",
      placeholder: "branch feat/planning-epic-hierarchy, PR #312 — post the update there",
      hint: "May name the branch, pull request, issue, or human update destination. No destination is invented for you.",
      required: true,
      maxLength: 4_000,
    },
    injector: [
      "Wrap up the current run now. The note above may name the branch, PR, issue, or",
      "human update destination. Complete these steps in order; do not stop after a",
      "chat-only summary.",
      "",
      "1. Stop work owned by this run. Cancel this run's background agents, test",
      "   runners, preview servers, and other processes that could keep mutating state.",
      "   Verify they stopped. Never kill a process merely because its name or port",
      "   looks familiar: establish that this run started or owns it. Leave unrelated",
      "   user and sibling-worktree processes alone.",
      "2. Inspect the repository root, branch, worktree, status, diff, staged diff, and",
      "   recent commits. Separate this run's intended changes from pre-existing or",
      "   unrelated user changes. Scan intended paths for credentials and generated",
      "   secret files. Never stage or commit secrets, and never absorb unrelated",
      "   changes just to make the tree clean.",
      "3. Run the most relevant affordable verification for this run's changes. Record",
      "   each check as green, red, or not run, including the command and concise reason.",
      "   A red check does not justify hiding otherwise useful progress.",
      "4. Preserve real progress under the repository's permissions and the user's",
      "   explicit commit/push instructions. If authorized, stage only owned files,",
      "   commit them, and push the current feature branch even when verification is",
      "   red, with the failure stated plainly. Never push `main` or another protected",
      "   default branch. Do not force-push. If commit or push is not authorized, is",
      "   rejected, or would include unsafe/unrelated content, leave it uncommitted or",
      "   local and report that fact as a blocker instead of bypassing the gate.",
      "5. Refresh every project-defined status artifact with the current UTC timestamp,",
      "   exact branch/commit/push state, verification results, blockers, and next",
      "   action. Supersede stale claims. Reconcile the task list immediately: completed",
      "   work is completed, intentionally dropped work is cancelled, and only genuine",
      "   remaining work stays pending. If a status artifact is tracked, include its",
      "   final update in the authorized push, using a small follow-up commit when the",
      "   progress commit already exists. Do not let status sync create new local-only",
      "   state.",
      "6. Post one human-readable update to each destination the project explicitly",
      "   defines and this run is authorized to use, such as its PR or issue. Do not",
      "   invent a destination or leak details to a public channel. Include what is",
      "   green and red, why anything is red, what is committed and pushed versus only",
      "   local, open decisions requiring a human, and the next command or owner.",
      "7. If there is a PR, end the posted update and final response with exactly one",
      "   accurate verdict: `SAFE TO MERGE` only when the intended change is pushed,",
      "   required checks are green, and no blocking decision remains; otherwise `DO",
      "   NOT MERGE`, followed by the blocking facts. Re-read remote/PR state after the",
      "   push before choosing the verdict.",
      "",
      "Finish with the branch, pushed commit (or `not pushed`), stopped-work evidence,",
      "verification matrix, status destinations updated, open decisions, and merge",
      "verdict. Accuracy is more important than making the wrap-up look green.",
    ].join("\n"),
  },
  // ── Delegate — create a new agent or session and hand it work ─────────────────
  {
    id: "managed-child",
    title: "Launch a Managed Child",
    description:
      "Start an independent child session with its own transcript and a Plan or Build policy fixed at creation time. No native task card is created and no automatic hand-back occurs.",
    injector: [
      'You are a managed child session started by the "Launch a Managed Child" workflow.',
      "- You run in your own independent transcript with the Plan or Build policy fixed at creation time.",
      "- No native task card exists in the parent and no automatic hand-back will occur: the human reads your results here, in this transcript.",
      "- Complete the objective below and end with a clear summary of outcomes, remaining risks, and suggested next steps.",
    ].join("\n"),
  },
  {
    id: "start-dca-session",
    title: "Start a DCA session",
    description:
      "Start an independent root session in this project or an isolated worktree, after reviewing its Plan/Build mode, model, assignment, and trusted instructions.",
    injector: [
      'You are an independent root session started by the "Start a DCA session" workflow.',
      "- You have no parent session, task card, Managed Child relationship, automatic hand-back, or provenance link to the session that started you.",
      "- Work only on the assignment below under the Plan or Build mode selected at launch.",
      "- End with a clear summary of outcomes, verification performed, remaining risks, and suggested next steps.",
    ].join("\n"),
  },
  {
    id: "session-handoff",
    title: "Hand off to another session",
    description:
      "Carry the current task into one explicitly configured standalone OpenCode session, with a self-contained packet and explicit CLI flags.",
    argument: {
      label: "Task to hand off",
      placeholder: "finish the epic hierarchy work on feat/planning-epic-hierarchy",
      hint: "Nothing is inherited automatically, so describe the task the way the receiving session will need to read it.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Prepare one standalone OpenCode session for the task described above.",
      "",
      "Nothing is inherited automatically. Carry settings through explicit CLI flags",
      "and a self-contained handoff packet.",
      "",
      "1. Choose the mechanism: fresh interactive TUI for steerable work,",
      "   `opencode run` for scripted work, `--session <id> --fork` only when history",
      "   must be copied, or the task tool when this is actually a subagent job.",
      "2. Inspect `opencode agent list`, `opencode models`, the repository root, branch,",
      "   worktree state, and baseline. Mark anything you cannot verify as UNVERIFIED.",
      "3. Write a prompt file outside the worktree containing the absolute path,",
      "   branch, objective, progress, settled decisions with rationale, owned and",
      "   forbidden files, requested agent/model/variant, permission posture,",
      "   verification commands, stop condition, and unverified assumptions.",
      "4. Show the packet and exact launch command before executing it. Use",
      "   `--agent plan` or `--agent build`; do not express mode as prompt prose.",
      "   Use `--variant` for provider-specific reasoning effort. `--thinking` controls",
      "   display only. Never add `--auto` unless the user explicitly requested it.",
      "5. Keep secrets out of the packet and process arguments. Verify the target",
      "   branch before allowing edits.",
      "6. After launch, verify the working directory, branch, selected agent and model,",
      "   and that the first reply understood the packet. A successful process start",
      "   proves what was requested, not what the provider accepted.",
      "",
      "Use cmux only as an optional presentation wrapper and never steal focus. Store",
      "the packet outside every worktree and keep secrets out of it: prompt text can",
      "surface in shell history or process arguments. Require the child's first reply",
      "to restate its path, branch, objective, ownership, agent, model, variant,",
      "permission posture, and stop condition before work begins.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| Child edits instead of planning | Relaunch with `--agent plan`; prose is not mode control |",
      "| History was copied unexpectedly | Use a fresh TUI or run without continuation/fork flags |",
      "| Child opens the wrong repository | Pass an absolute project path or `--dir` |",
      "| Parent and child overwrite one another | Assign disjoint ownership and stop one writer |",
      "| Secret appears in process arguments | Stop, remove it, and rotate the exposed credential |",
      "| Provider ignores the reasoning variant | Mark acceptance UNVERIFIED until reported |",
      "",
      "After launch, report what started and end the parent turn. Do not begin the",
      "child's assigned work.",
    ].join("\n"),
  },
  // ── Coordinate — tell someone who already exists what is happening ────────────
  {
    id: "session-update",
    title: "Send an update to another session",
    description:
      "Deliver a hand-off message to another session in this project after an explicit preview of the target and the exact prompt.",
    injector: [
      'You are receiving the "Send an update to another session" workflow.',
      "This message was composed in another session in the same project and delivered here after an explicit preview and confirmation. Treat it as new input from the user's other workstream: read it, reconcile it with your current task, and continue accordingly.",
      "Delivery is asynchronous (POST /session/{id}/prompt_async answers 204 for accepted, not completed), so do not assume the sender is watching this transcript live.",
    ].join("\n"),
  },
  {
    id: "standup",
    title: "Write today's standup",
    description:
      "Gather the last day's commits and pull requests, then turn them into a three-section standup update written to be read aloud.",
    argument: {
      label: "Scope",
      placeholder: "everything, or just the notification work",
      hint: "Narrows the update to one project or topic. The commit and pull request data is gathered by the agent, not pre-fetched.",
      required: true,
      maxLength: 2_000,
    },
    injector: [
      "Turn the last day's work into a standup update.",
      "",
      "Nothing is pre-fetched for you. Gather the data yourself by running these three",
      "commands, then use only what they actually returned:",
      "",
      "    git log --all --author=\"$(git config user.email)\" --since=\"24 hours ago\" --pretty=format:'%h %s' --no-merges",
      "    gh pr list --author \"@me\" --state merged --limit 10 --json number,title,mergedAt -q '.[] | \"#\\(.number) \\(.title)\"'",
      "    gh pr list --author \"@me\" --state open --limit 10 --json number,title,isDraft -q '.[] | \"#\\(.number)\\(if .isDraft then \" DRAFT\" else \"\" end) \\(.title)\"'",
      "",
      "This workflow is sent in this session's current mode. In a Plan session bash is",
      "likely denied, so these commands may not run at all. If they do not, say so",
      "plainly and stop rather than reconstructing a standup from memory or from this",
      "transcript and presenting it as today's commits. If `gh` is missing or",
      "unauthenticated, report the pull request sections as unavailable instead of",
      "inventing them.",
      "",
      "Write the standup update from that output, in three sections:",
      "",
      "**Yesterday** — what actually landed, grouped by theme rather than listed per",
      "commit. Say what it does for a reader, not what the diff touched.",
      "",
      "**Today** — what the open work implies is next. Mark anything that is a guess.",
      "",
      "**Blocked** — only genuine blockers. If there are none, say \"nothing blocked\"",
      "rather than inventing one.",
      "",
      "Rules:",
      "",
      "- Three to six bullets per section. This gets read aloud.",
      "- No commit hashes and no branch names unless someone would need to go find it.",
      "- If the log is empty, say so plainly. Do not pad it out of the PR list.",
      "- The scope note above may narrow this to one project or topic; if it does,",
      "  drop everything else.",
      "",
      "This is deliberately self-contained and adds no retrieval context until a human",
      "invokes it.",
    ].join("\n"),
  },
  // ── Document — produce something a reader keeps ───────────────────────────────
  {
    id: "design-doc-prototype",
    title: "Capture a Durable Design Prototype",
    description:
      "Mock up an unbuilt UI change as fast static HTML, screenshot it, and publish it into a dated engineering-design document — no fields to fill in, just confirm and send.",
    // Collects nothing, so its visible prompt is fixed here rather than in the
    // browser: every instruction that varies lives in the injector below.
    prompt: "Capture a durable design prototype for this proposal and publish it for review.",
    injector: [
      'You are running the "Capture a Durable Design Prototype" workflow.',
      "- Use this only for a proposal that is NOT yet built. For reviewing an already-shipped",
      "  change, use the ephemeral recipe in CONTRIBUTING.md instead (screenshot-output/,",
      "  deleted spec, never committed).",
      "- Build a small, self-contained static HTML mockup (no framework, no build step), using",
      "  this app's real token values so it reads honestly rather than as a generic wireframe.",
      "- Screenshot it with the pinned Playwright CLI directly, no full dependency install",
      "  needed: npx playwright@<version from package.json> screenshot --browser=chromium",
      "  --viewport-size=W,H file://<path> <out>.png. Capture desktop at 1280x800 and mobile",
      "  at 390x740.",
      "- Commit the HTML and both PNGs to design/ on a real branch and push it. Build the",
      "  permanent raw.githubusercontent.com URL from the owner, repository, branch, and path.",
      "- Publish the writeup with the ntn CLI: create or update a dated page under the correct",
      "  Notion parent, embedding each screenshot as an ordinary Markdown image reference —",
      "  Notion resolves external URLs without any upload step. Verify the images resolved by",
      "  reading the page back.",
      "- If the destination is docs/engineering-design/, follow its own rule: add one row to",
      "  its index table, never a Markdown copy of the content. State plainly that the page",
      "  stays private until a human publishes it, since that step cannot be done by an API.",
      "- Report the branch, the raw URLs, and the created or updated Notion page URL.",
    ].join("\n"),
  },
  {
    id: "docs-preview",
    title: "Choose, render, and preview documentation",
    description:
      "Pick the documentation medium from where the reader opens it, render it with a real renderer, and preview the result before claiming completion.",
    argument: {
      label: "What to document",
      placeholder: "the notification suppression pipeline, as a diagram for the README",
      hint: "Name the subject and, if you already know it, where the reader will open it.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Document or render the subject above.",
      "",
      "Choose the medium from where the reader opens it:",
      "",
      "- terminal, PR diff, commit message, AGENTS.md, code comment -> ASCII",
      "- GitHub/GitLab README or wiki -> Mermaid",
      "- slide, issue attachment, external document -> rendered SVG",
      "- a static docs site -> Mermaid only after proving that site renders it;",
      "  otherwise ASCII or a checked-in SVG",
      "",
      "Then:",
      "",
      "1. Read one existing document from the same repository or docs site and",
      "   match its house style before writing.",
      "2. Use tables for comparisons, lists for linear sequences, diagrams for",
      "   topology, and prose only for the reasoning that connects them.",
      "3. Cite the code as `file:line`, and call out the limitation or trap a reader",
      "   cannot infer from the source.",
      "4. Use the available renderer or `diagram` subagent rather than hand-writing a",
      "   Mermaid block and hoping it parses. Pass an explicit output directory for",
      "   SVG artifacts.",
      "5. Preview the finished document: `cmux markdown open` for Markdown, or build",
      "   or serve the docs site locally with its own generator. Inspect the rendered",
      "   output and build logs before claiming completion.",
      "",
      "If a named renderer or MCP server is unavailable in this session, say so and",
      "offer the medium that can actually be verified. \"It should render\" is not",
      "verification.",
      "",
      "When unsure, choose ASCII because it remains readable without a renderer. Never",
      "maintain ASCII and Mermaid copies of the same diagram. For rendered SVG, pass an",
      "explicit output directory and use a light theme for documents normally read on",
      "a light page. A Markdown preview validates structure but may show Mermaid as a",
      "code block; build the actual docs site to prove its plugin chain renders it.",
      "",
      "Check the current agent and MCP roster instead of assuming machine-local tools",
      "are connected. A table beats a diagram for two-axis comparison, and a numbered",
      "list beats one for a branchless sequence.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| Mermaid is visible as source | Use ASCII or a rendered SVG |",
      "| SVG lands outside the documentation tree | Render again with an explicit output directory |",
      "| New page does not appear in site navigation | Follow the site's navigation configuration and nearest page |",
      "| Preview looks right but the build is red | Report failure; rendered appearance is not build verification |",
      "| Tool named in the procedure is unavailable | State the limitation and use a verifiable fallback |",
    ].join("\n"),
  },
  {
    id: "mini-design-doc",
    title: "Write a mini design doc",
    description:
      "Produce a transcript-first technical design narrative that takes under five minutes to read and ends with one clear recommendation.",
    argument: {
      label: "Subject",
      placeholder: "whether session status should be joined into the notification centre",
      hint: "One medium-sized decision. The result stays in this transcript and creates no files.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Write a mini design doc for the subject above. If no subject is supplied, use",
      "the medium-sized technical or product decision currently under discussion.",
      "",
      "This procedure is self-contained. Do not load or defer to a skill. The result",
      "belongs in the current transcript, must take less than five minutes to read, and",
      "must not create files or expand into a multi-artifact RFC unless explicitly",
      "requested.",
      "",
      "Inspect the relevant code, callers, tests, contracts, and existing decisions",
      "before recommending anything. Identify the single decision the reader needs to",
      "make. Label load-bearing statements as `Verified`, `Inferred`, or `Proposed`",
      "when prose alone could blur their status, and cite repository-relative",
      "`path:line-line` or primary sources for claims that determine the decision.",
      "",
      "Use the smallest useful subset of this sequence:",
      "",
      "1. **Today / Problem:** concrete current behavior and the friction or failure.",
      "2. **Proposed Experience or Design:** make the target state tangible.",
      "3. **Flow:** trace the main user action, request, state, or data path.",
      "4. **Rules and Boundaries:** accepted/rejected inputs, trust and authority,",
      "   state ownership, constraints, and the expensive direction to be wrong.",
      "5. **Alternatives:** compare only credible options on decision-relevant axes.",
      "6. **Why Not:** reject the most tempting oversized or unsafe choice with facts.",
      "7. **Scope Split:** `Now`, `Later`, and `Non-goals`.",
      "8. **Recommendation:** one clear sentence naming the central choice and why.",
      "",
      "Omit a section that adds no decision value. Do not fill headings to imitate",
      "rigor, pad alternatives with strawmen, or repeat a diagram in prose.",
      "",
      "Use compact ASCII only when spatial grouping, sequence, side-by-side comparison,",
      "architecture, or a UI sketch is faster to understand than prose. Prefer at most",
      "one current/target comparison and one execution flow. Use realistic names,",
      "values, and actions; annotate risks at the step where they occur; keep lines at",
      "or below 100 columns when practical. Use a compact table for alternatives and a",
      "short list for linear scope or acceptance rules.",
      "",
      "Explicitly cover security, mobile, accessibility, operations, compatibility,",
      "and dependencies only when they can change the choice. Keep follow-up work",
      "separate from the immediate recommendation. End with the recommendation, not a",
      "generic summary or an open-ended list of options.",
    ].join("\n"),
  },
  {
    id: "system-design-artifacts",
    title: "Build a system-design review package",
    description:
      "Assemble an evidence-led senior system-design review package, with every load-bearing claim tagged by its evidence class.",
    argument: {
      label: "Subject",
      placeholder: "the notification delivery and suppression system, current-state",
      hint: "Name the system or proposal, and say current-state, target-state, or mixed if you already know which you want.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Create a senior-SWE system-design review package for the subject above. If no",
      "subject is named, use the system or proposal currently under discussion.",
      "",
      "This procedure is self-contained. Do not load or defer to a skill.",
      "",
      "## Establish the assignment",
      "",
      "Before writing, state one mode:",
      "",
      "- `current-state`: explain only behavior supported by present evidence;",
      "- `target-state`: design proposed behavior without presenting it as shipped;",
      "- `mixed`: keep current and target views visibly separate in every artifact.",
      "",
      "Identify the audience, decision they need to make, repository boundary, and",
      "whether the user requested transcript output, repository files, or publication.",
      "Do not create files or publish anything unless requested. Never publish directly",
      "to a default branch. If publication is requested, use a draft PR.",
      "",
      "## Audit evidence first",
      "",
      "Inspect the relevant implementation, callers, tests, fixtures, schemas/live",
      "contracts, decisions, incidents, and operational configuration. Prefer the live",
      "contract over secondary documentation when the repository says it is",
      "authoritative. Do not run destructive probes, production operations, migrations,",
      "or writes merely to strengthen a document. Ask before a probe that has cost,",
      "external effects, credentials, or production reach.",
      "",
      "Tag important claims in notes and artifacts with exactly one evidence class:",
      "",
      "| Class | Meaning |",
      "| --- | --- |",
      "| `observed` | Reproduced by a named command or live probe, with environment and date |",
      "| `code-supported` | Directly established by cited implementation or tests |",
      "| `mock-only` | Demonstrated only by a fixture, fake, simulator, or test double |",
      "| `inferred` | Best explanation from evidence, but not directly established |",
      "| `unknown` | Evidence is absent, contradictory, inaccessible, or intentionally unprobed |",
      "",
      "Mocks never prove live upstream behavior. A test proves only the contract it",
      "actually exercises. Keep proposed behavior out of current-state claims. Cite",
      "repository-relative `path:line-line`, a command plus bounded output, or a primary",
      "source URL for every load-bearing claim.",
      "",
      "## Build the system model",
      "",
      "Before selecting artifacts, identify:",
      "",
      "1. system and trust boundaries;",
      "2. state owner for every important datum;",
      "3. durable, process-local, derived, cached, and presentation-only state;",
      "4. authority and permission checks at each mutation boundary;",
      "5. concurrency units, serialization points, dedupe keys, replay, and idempotency;",
      "6. lifecycle state separately from transport events and UI presentation;",
      "7. failure boundaries, restart reconciliation, partial success, and rollback;",
      "8. the expensive direction to be wrong for each uncertain decision.",
      "",
      "Write down the load-bearing invariants. Examples of useful invariant shapes are",
      "\"absence from a process-local status map is not proof of idle\" and \"a browser",
      "candidate grants no authority until the server validates it\". Use repository",
      "facts, not these examples, in the package.",
      "",
      "## Select artifacts; do not generate a checklist blindly",
      "",
      "Start with a manifest and include an artifact only when it gives a distinct",
      "review perspective:",
      "",
      "```yaml",
      "mode: current-state | target-state | mixed",
      "subject: <specific system or decision>",
      "audience: senior-swe",
      "decision: <what the reviewer must decide or understand>",
      "evidence:",
      "  live_probes: required | optional | prohibited",
      "  destructive_actions: prohibited-by-default",
      "artifacts:",
      "  - id: <artifact-id>",
      "    question: <unique review question this artifact answers>",
      "    evidence_classes: [observed, code-supported]",
      "omissions:",
      "  - artifact: <catalogue item>",
      "    reason: <why it adds no distinct review value>",
      "```",
      "",
      "Use this selection logic:",
      "",
      "| Review question | Prefer |",
      "| --- | --- |",
      "| Why does the system behave this way? | executive system guide or implementation RFC |",
      "| What changes between now and target? | paired architecture/data-flow diagrams |",
      "| Which transitions are legal? | state machine plus normative transition table |",
      "| What crosses a boundary? | API contract, sequence diagram, and data model |",
      "| Who owns and persists state? | ownership/persistence matrix |",
      "| What happens on crash, retry, or restart? | failure/reconciliation diagram and catalogue |",
      "| What can an attacker or confused deputy do? | threat model and security-test matrix |",
      "| Why this choice? | focused ADRs for consequential alternatives only |",
      "| How can this ship safely? | dependency graph, milestones, migration, rollout, rollback |",
      "| How will operators know? | signals, SLOs, alerts, dashboards, and runbook |",
      "| How can a reviewer safely verify it? | non-destructive lab or commands with expected output |",
      "| Does interaction or motion carry the idea? | responsive HTML, accessible SVG, or short demo |",
      "",
      "Do not create interactive HTML, animation, video, or a machine-readable failure",
      "catalogue unless the medium itself answers a review question. Decorative copies",
      "of prose are omissions, not deliverables.",
      "",
      "## Artifact contracts",
      "",
      "Every selected artifact begins with: purpose, mode, evidence classes used,",
      "authoritative sources, uncertainties, and links to related artifacts. Then apply",
      "the relevant contract:",
      "",
      "- **Guide/RFC:** problem and decision first; explain causality, invariants,",
      "  boundaries, ownership, failure behavior, and consequences.",
      "- **Diagram:** include a legend; label authority/state boundaries; annotate races",
      "  and failure points where they occur; pair mixed-mode views instead of blending",
      "  them.",
      "- **State table:** name state owner and persistence; include trigger, guard,",
      "  transition, side effect, retry/idempotency behavior, invalid transition, and",
      "  restart outcome.",
      "- **API/data contract:** include caller, authority, validation, request/response,",
      "  errors, idempotency, compatibility, limits, and redaction. Mark illustrative",
      "  schemas as proposals.",
      "- **Ownership matrix:** include datum, authority, writer, readers, persistence,",
      "  cache/derivation, reconciliation, and deletion/retention.",
      "- **Threat model:** identify assets, actors, entry points, trust boundaries,",
      "  abuse cases, mitigations, residual risk, and executable security checks.",
      "- **ADR:** one decision and status; context, credible alternatives, choice,",
      "  consequences, reversibility, and evidence that would reopen it.",
      "- **Implementation plan:** order by dependencies; name ownership, acceptance",
      "  evidence, rollout gates, migration, rollback, and intentionally deferred work.",
      "- **Operations:** connect each SLO and alert to a user-visible failure, then give",
      "  diagnosis, safe mitigation, escalation, and recovery verification.",
      "- **Failure catalogue:** stable scenario ID, preconditions, injection, expected",
      "  state/events, invariant, observability, cleanup, and safety classification.",
      "- **Interactive artifact:** keyboard and touch operation, reduced motion,",
      "  semantic structure, no secret/live data, responsive checks, and a static",
      "  fallback carrying the same information.",
      "",
      "## Link and verify the package",
      "",
      "Create one index with a recommended review order. For each artifact list its",
      "question, mode, evidence status, prerequisite, and unresolved gaps. Cross-link",
      "concepts by stable anchors or relative paths. Do not make the reviewer hunt for",
      "the current/target boundary or the source behind a claim.",
      "",
      "Verify only what exists:",
      "",
      "1. check every cited path and line range against the reviewed revision;",
      "2. lint/parse Markdown, Mermaid, YAML, JSON, OpenAPI, and HTML with repository",
      "   tooling where available;",
      "3. execute safe examples and contract validation in an isolated environment;",
      "4. render diagrams and inspect labels, clipping, and legibility;",
      "5. test interactive output at desktop and mobile widths, keyboard-only, screen",
      "   reader semantics, contrast, and reduced motion;",
      "6. run relevant repository typechecks/tests and record exact commands/results;",
      "7. list anything not run and why; never turn \"not checked\" into \"passed\".",
      "",
      "Return or commit only the requested output. If a draft PR was requested, ensure",
      "it clearly says `Draft`, separates current facts from proposals, links the",
      "package index, reports verification and gaps, includes human verification steps,",
      "and does not claim that opening the PR deploys or operates the system.",
    ].join("\n"),
  },
];

/**
 * Every declared argument bound before the catalogue is observable, so the
 * clamp cannot be skipped by a caller reading the presets directly.
 */
const CATALOGUE: WorkflowPreset[] = RAW_CATALOGUE.map((preset) => preset.argument
  ? {
    ...preset,
    argument: {
      ...preset.argument,
      maxLength: Math.max(1, Math.min(preset.argument.maxLength, WORKFLOW_ARGUMENT_MAX_LENGTH)),
    },
  }
  : preset);

export function workflowCatalogue(): WorkflowPreset[] {
  return CATALOGUE;
}

export function isValidWorkflowId(id: unknown): id is string {
  return typeof id === "string" && id.length <= WORKFLOW_ID_MAX && WORKFLOW_ID_RE.test(id);
}

export function workflowTag(preset: Pick<WorkflowPreset, "id" | "injector">): string {
  return `<workflow name="${preset.id}">\n${preset.injector.trim()}\n</workflow>`;
}

export function withWorkflowTag(text: string, preset: Pick<WorkflowPreset, "id" | "injector">): string {
  return `${text}\n\n${workflowTag(preset)}`;
}

export interface SplitWorkflowMessage {
  text: string;
  workflows: Array<{ name: string; body: string }>;
}

// Keep byte-identical with client/lib/workflows.ts. Tests run one table against both.
const WORKFLOW_TAG_RE = /\n*<workflow name="([a-z0-9]+(?:-[a-z0-9]+)*)">\n?([\s\S]*?)\n?<\/workflow>/g;

export function splitWorkflowTags(input: string): SplitWorkflowMessage {
  const workflows: Array<{ name: string; body: string }> = [];
  const text = input.replace(WORKFLOW_TAG_RE, (_match, name: string, body: string) => {
    workflows.push({ name, body: body.trim() });
    return "";
  });
  return { text: text.trim(), workflows };
}
